#!/bin/bash
# This file is part of Cockpit.
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

set -eu

BASE=$(cd $(dirname $0)/../; pwd -P)
MAKE_SRPM=$BASE/tools/make-srpm

usage()
{
	echo "usage: make-rpms" >&2
    exit 2
}

warning()
{
    echo "make-rpms: $@" >&2
}

while getopts "" o; do
    case "${o}" in
        *)
            usage
            ;;
    esac
done
shift $(expr $OPTIND - 1)

if test $(id -u) != 0; then
    warning "run this command as root"
    exit 1
fi

SRPM=$($MAKE_SRPM)
REPO=$BASE/mock/tree

if [ ! -d $REPO/objects ]; then
    mkdir -p $REPO
    ostree --repo=$REPO init
    ostree --repo=$REPO remote add --set=gpg-verify=false origin http://localhost/cockpit-tree
fi

build()
{
    target=$1
    shift

    $BASE/tools/make-container $target-devel $@

    container=$BASE/build/containers/$target
    cp $SRPM $container/tmp/$SRPM
    systemd-nspawn -D $container /usr/bin/rpmbuild --rebuild /tmp/$SRPM >&2
    find $container/root/rpmbuild/ -name '*.rpm'
}

set -x
if [ $# -eq 0 ]; then
    while read target commit; do
        build $target $commit
    done < $BASE/tools/build-targets
else
    for target in $@; do
        build $target
    done
fi
